include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9325
  bind-hostname = "0.0.0.0"
}

queues {
  boilerplate-api-lambda-dev-queue {
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    deadLettersQueue {
      name = "boilerplate-api-lambda-dev-queue-dlq"
      maxReceiveCount = 3
    }
  }

  boilerplate-api-lambda-dev-queue-dlq {
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
}
